### ISSUE TITLE
Use the same documentation window as lsp-ui-doc

### ISSUE THREAD

**Issue by benwainwright** [expez/company-quickhelp#107]
Hi there!

When I setup **company-quickhelp**, it appears to be displaying the docs in a tiny UI tooltip:

![image](https://user-images.githubusercontent.com/3321885/85826496-97dea500-b77c-11ea-9d0f-6c9013f85a80.png)

Whereas when I hover on a symbol, **lsp-ui-doc** displays documentation in what I assume is an emacs popup buffer: 

![image](https://user-images.githubusercontent.com/3321885/85826610-bd6bae80-b77c-11ea-95c2-a5f541262813.png)

I'm not a massive fan of the UI tooltip, and I note that in the docs in this repo, the screenshots seem to show an emacs buffer. Is there a way of configuring **company-quickhelp** not to use the tooltip?

**Comment by dgutov** [comment]
We could switch to child frames for rendering, and probably will in the future.

But we wouldn't match lsp-ui's decorations still, because it uses its own rendering code, with colors etc configured solely for lsp-ui's use. Perhaps you should just disable this package and request a similar feature to be incorporated into lsp-ui.

Or install `company-posframe`, it has a child frame based documentation popup.
