### ISSUE TITLE
the bottom text is half hide in company-quickhelp pos-tip

### ISSUE THREAD

**Issue by stardiviner** [expez/company-quickhelp#21]
Here is the screenshot.
![company-quickhelp pos-tip some string hide](https://cloud.githubusercontent.com/assets/378699/8864668/474727d2-31d7-11e5-80e7-d217ed0bb2a4.png)

**Comment by expez** [comment]
Hi

This is the first time I've seen this bug.  I can't think of anything in `company-quickhelp` which could cause this, because we don't tell `pos-tip` (the library displaying the popup) how much space it can take up.  In fact, I added the variable `company-quickhelp-max-lines` a while back because the popup will take up however much space it needs to display itself, which can lead to really big popups for correspondingly large docstrings.  `company-quickhelp-max-lines` does it's thing by limiting the amount of text we're telling `pos-tip` to display, not by restricting its size.

I'm sorry to tell you that I think this is likely caused by something in your `.emacs.d` or some other particulars related to your system.  The only thing I can advice is trying to reproduce from `emacs -q` and then bisecting your `.emacs.d` if the popup looks alright.

**Comment by stardiviner** [comment]
@expez You're right. I can't reproduce it in `emacs -Q`.
