### ISSUE TITLE
Will it ever be possible to support this popup on a Non-GUI Emacs frame?

### ISSUE THREAD

**Issue by computersarecool** [expez/company-quickhelp#43]
Auto-complete does this and I am curious if it could ever be possible to support the helpful pop ups on a non-GUI emacs?

**Comment by expez** [comment]
Yeah it would be possible.  You can do it today.  Just fork this project and use `popup.el` instead of `postip`.  `popup.el` is what auto-complete uses to display its popups.

Why am I not doing this?  I don't like `popup.el` (and I always run a GUI now).  I used it for a long time when I was an auto-complete user and it was one of the reasons I felt quite motivated to switch over to company.
