### ISSUE TITLE
Cann't show quickhelp in golang!

### ISSUE THREAD

**Issue by hello-code** [expez/company-quickhelp#45]
It works in elisp-mode,but it didn't work in golang.
This is my emacs config:

```
(use-package company-quickhelp
  :ensure t
  :config
  (company-quickhelp-mode 1)
  (setq company-quickhelp-delay 0.2)
  )
(provide 'init-company-quickhelp)
```

Thanks for your help!

**Comment by expez** [comment]
Since you get documentation in elisp, but not in golang this means there's no backend for company-mode to hook into to get documentation.  You need to find a company backend for golang.

The reason it works for elisp is that the elisp backend is included in company.

**Comment by hello-code** [comment]
Thanks for your reply!
Do you mean "company-go.el"?
This is my golang config:

```
(use-package go-mode
  :ensure t
  :defer t
  :init
  ;; format the current buffer
  (add-hook 'go-mode-hook '(lambda () (local-set-key (kbd "C-c C-f") 'gofmt)))

  ;; Gocode autocomplete
  ;;(add-hook 'go-mode-hook 'company-mode)
  (add-hook 'go-mode-hook
            '(lambda()
               (set (make-local-variable 'company-backends)'(company-go))
               (company-mode)))
)


```

**Comment by expez** [comment]
Yes.  Company-go doesn't have support for documentation, which is why you're not seeing any documentation.

Compare these two backend definitions:

https://github.com/nsf/gocode/blob/master/emacs-company/company-go.el#L190-L205
https://github.com/company-mode/company-mode/blob/master/company-elisp.el#L199-L222

company-go doens't respond to the `doc-buffer` command.

**Comment by hello-code** [comment]
Thank you very much!

**Comment by nikclayton** [comment]
FYI: https://github.com/nsf/gocode/issues/415
