### ISSUE TITLE
vertical truncating of single-line help

### ISSUE THREAD

**Issue by gaydenko** [expez/company-quickhelp#49]
Hi! Single line help is vertically truncated at the bottom. That is I don't see lower half of the text.
![signature-truncated](https://cloud.githubusercontent.com/assets/3740016/18808195/41b1f4c6-8264-11e6-96df-760b2707dcdb.png)
Emacs 25.1 under Manjaro Linux/KDE is in use.

**Comment by expez** [comment]
I rely on pos-tip to show the help text, which again delegates to various subsystems.  This seems to be a bug further down the stack.  You could try opening a bug over at pos-tip, but I'm guessing this is in the layer below that again.

**Comment by gaydenko** [comment]
https://github.com/syohex/pos-tip isn't open for issues. So I'm in doubt wrt the next step. Can you, please, suggest something else to escalate the issue? Or, probably, some dirty workaround can be added to company-quickhelp, say, adding line end to single-line text...

**Comment by expez** [comment]
[Here](https://github.com/pitkali/pos-tip/issues) is the pos-tip we rely on.  That repo is open for issues.

> Or, probably, some dirty workaround can be added to company-quickhelp, say, adding line end to single-line text...

Since you're the only one affected by this I don't want to start adding hacks that affect every user and the quality of the code base.

Emacs is so flexible that you can override any function in this package to do exactly what you want.

One way to fix this is to add a little elisp to the end of this function:

``` el
(defun company-quickhelp--doc (selected)
  (cl-letf (((symbol-function 'completing-read)
             #'company-quickhelp--completing-read))
    (let* ((doc (company-call-backend 'doc-buffer selected))
           (doc-and-meta (when doc
                           (company-quickhelp--doc-and-meta doc)))
           (truncated (plist-get doc-and-meta :truncated))
           (doc (plist-get doc-and-meta :doc)))
      (unless (string= doc "")
        (if truncated
            (concat doc "\n\n[...]")
          doc)))))
```

To make sure `doc` is always padded with a few extra lines, or whatever.

**Comment by gaydenko** [comment]
Thanks for the workaround! - I have added the function (with minor modification) to init.el - it helps!
