### ISSUE TITLE
Error running timer `company-quickhelp--show': (error "No buffer named test 001")

### ISSUE THREAD

**Issue by kaaresl** [expez/company-quickhelp#65]
I can't get this to work in [php-mode](https://github.com/ejmr/php-mode) and using the  [ac-php](https://github.com/xcwen/ac-php) completion source in company mode. Any selected suggestion gives this message:

```
Error running timer `company-quickhelp--show': (error "No buffer named test 001")
```

**Comment by expez** [comment]
Sorry to hear that!

Can you do: <kbd>M-x</kbd> toggle-debug-on-error <kbd>RET</kbd> and provide a stacktrace that is a bit longer?

**Comment by kaaresl** [comment]
```
Debugger entered--Lisp error: (error "No buffer named test 001")
  company-quickhelp--doc-and-meta("test 001")
  company-quickhelp--doc(#("setDate(" 0 8 (summary "DateTime" ac-php-access "public" ac-php-return-type "DateTime" ac-php-help "int $year,int $month,int $day" ac-php-tag-type "m" ac-php-from "DateTime")))
  company-quickhelp--show()
  apply(company-quickhelp--show nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 nil company-quickhelp--show nil idle 0])
```
I also noticed this only happened after installing the `company-php` package from melpa.

**Comment by expez** [comment]
`company-quickhelp--doc` is expecting a completion candidate as its argument. E.g. `setDate` would be a valid input.  It would then ask the company backend for the documentation associated with that completion candidate, which it would then display.  Instead it's receiving this: `#("setDate(" 0 8 (summary "DateTime" ac-php-access "public" ac-php-return-type "DateTime" ac-php-help "int $year,int $month,int $day" ac-php-tag-type "m" ac-php-from "DateTime"))`

To me, it looks like you're having some problem with your company backend.  I can only speculate that this is happening because you have both `ac-php` and `company-php` installed at the same time or that either or both of those backends are malfunctioning / unfinished.

**Comment by xcwen** [comment]
i not know how   to fix this bug:<

**Comment by cpitclaudel** [comment]
Looks like the underlying issue (https://github.com/xcwen/ac-php/issues/47) was fixed :)

**Comment by cyrialize** [comment]
Could one of you post an example config for using company-php and company-quickhelp? I cannot get quickhelp working with this package. I also do not get the messages mentioned when going over any selection.

**Comment by cpitclaudel** [comment]
As far as I can tell, company-php doesn't offer documentation at all, does it?
If so, company-quickhelp won't be able to do anything useful.

**Comment by cyrialize** [comment]
Thanks, I'll comment on the issue in ac-php.
