### ISSUE TITLE
Conflict with clj-refactor

### ISSUE THREAD

**Issue by blak3mill3r** [expez/company-quickhelp#79]
Through a lot of trial and error, I've narrowed it down to this...

If I comment out

```elisp
(use-package clj-refactor)
```

Then I get `company-quickhelp-mode` popups with cider, otherwise they do not appear. No sign of errors in the elisp, nothing much for me to dig into. I'm happy to help debug, I just don't know where to begin. I really love the functionality of this package... having to choose between this and `clj-refactor` for now is breaking my heart ;)

```
emacs --version
GNU Emacs 27.0.50

uname -a
Linux magnathorax 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

                  [cider/cider-nrepl "0.16.0"]
                  [refactor-nrepl "2.4.0-SNAPSHOT"]

```

I'm using `straight.el`. My elisp packages are all tracking `master` and updated just now. I downgraded the `cider-nrepl` middleware to `0.16.0` because the snapshot wasn't working for me at all, other than that I believe everything is bleeding-edge.

**Comment by expez** [comment]
clj-refactor doesn't use `company` in any way, nor does it use anything else to create popups that might conflict.

I'm using `clj-refactor` and `cider` along with `company-quickhelp` myself every day, as do quite a few others, so this problem is unfortunately somethings specific to your emacs config.

I suggest looking into whatever `use-package` expands into and then digging into each constituent line to find the exact problem.

**Comment by blak3mill3r** [comment]
Good to know! Thanks for the guidance.
