### ISSUE TITLE
How to enlarge the font?

### ISSUE THREAD

**Issue by NightMachinery** [expez/company-quickhelp#81]
Is there any way I can enlarge the font of the tooltip? 
![image](https://user-images.githubusercontent.com/36224762/37247843-58e43a8e-24d7-11e8-835a-2244878ebd29.png)

**Comment by cpitclaudel** [comment]
Yes, it should be possible to customize the `tooltip` face.  You might have to set `x-gtk-use-system-tooltips` to `nil` first.

**Comment by cpitclaudel** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/elisp/Tooltips.html

**Comment by NightMachinery** [comment]
@cpitclaudel There is no such variable:
![image](https://user-images.githubusercontent.com/36224762/37253968-f89bfdac-254d-11e8-8ad2-a88a15e3f4fe.png)

**Comment by cpitclaudel** [comment]
That's OK: did you customize the tooltip face ?

**Comment by NightMachinery** [comment]
@cpitclaudel It is currently like this:
![image](https://user-images.githubusercontent.com/36224762/37254031-d283b74e-254e-11e8-891c-db13dabe428a.png)
But as you see the colors haven't taken effect.
And I don't see an option for font size?

**Comment by NightMachinery** [comment]
BTW these colors were like this from the start (that EDITED is because I changed font family)

**Comment by NightMachinery** [comment]
I have made the face like this but it has no effect:
![image](https://user-images.githubusercontent.com/36224762/37254124-84341808-254f-11e8-900f-c3f605963cac.png)

**Comment by cpitclaudel** [comment]
Sorry, in that case I don't know (I'm not on mac).  But this doesn't sound much like a company-quickhelp issue :/

**Comment by NightMachinery** [comment]
Was this solved somehow? If not, keeping it open is better. Someone might
know a fix, after all.

**Comment by cpitclaudel** [comment]
The problem isn't in company-quickhelp, but in the way your Emacs displays tooltips (it's using native tooltips, which are not configurable).  I'm not sure what the right way is to tell Emacs to use it's own tooltips on mac.

**Comment by rightpad** [comment]
I'm also experiencing this issue which is preventing me from using this package. In #80  @cpitclaudel made mention of replacing pos-tip with pos-frame by overriding pos-tip's entry points. I'm a relatively new emacs user so I don't have the knowledge on how to do that, so I think including some sample instructions in the README would help mac users a lot. I currently use flycheck-posframe instead of flycheck-postip and it work great cross-platform.

**Comment by francisbouvier** [comment]
Hi. I know this issue is old but I experience the same problem.

I'm using Emacs 28.1 on MacOS (so no `x-gtk-use-system-tooltips`). I have customized the `tooltip` face (backgound color blue and font height 1.5).

- `company-mode` is taking in account both font height and background color
- `company-quickhelp` is taking in account just background color

<img width="691" alt="Screenshot 2022-09-29 at 14 05 57" src="https://user-images.githubusercontent.com/5114029/193027078-537c6de5-c694-45d7-83c1-ae2062d4d8b3.png">

So I believe there is a problem in how `company-quickhelp` (or `pos-tip`) use face height.
I believe https://github.com/company-mode/company-quickhelp/pull/103 is solving the problem (however I haven't try) by defining a custom `company-quickhelp-face`.

**Comment by dgutov** [comment]
When you say "taking in account just background color", what do you mean?

In the screenshot the text in the tooltip is noticeably larger than the text in the main window. Isn't that your customization?

**Comment by francisbouvier** [comment]
Yes the text of the `company` tooltip is at the good size.

But the text of the `company-quickhelp` is not, the one saying "_Compares two slices and returns wether they are equal._" on the right.

**Comment by dgutov** [comment]
Now I see what you mean, thanks.

It seems like the `tooltip` face is only honored by `tooltip-show`, whereas `pos-tip` calls `x-show-tip` directly.

I suggest you actually try #103 and see whether is solves the problem for you. And doesn't add any obvious bug on top.
