### ISSUE TITLE
Work with jedi? 

### ISSUE THREAD

**Issue by fxfactorial** [expez/company-quickhelp#84]
There is a company-jedi layer, can there also be one for the popup? 

https://github.com/tkf/emacs-jedi/issues/307#issuecomment-378000979

**Comment by cpitclaudel** [comment]
Are you sure you're in the right repo?  Or maybe I'm misunderstanding what you're asking? :)

**Comment by fxfactorial** [comment]
Yes, misunderstanding. 

Jedi can put documentation for python docstrings in a popup via autocomplete but not company. Company-jedi already exists as a company interface to jedi, I also would like a company version (this is quickhelp's role) for the popup that jedi does via autocomplete.

**Comment by expez** [comment]
If company-jedi works as it should, and you have company-quickhelp installed, then this should work out of the box.

If it does not, it might be because autocomplete is fighting with company over who gets to show a popup or something.

In any event, we just display company documentation in a popup, if it's available.  We're backend agnostic, so if there's a problem take it up with the company-jedi guys.

Best of luck!
